name: Django Company API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.12-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add --no-cache gcc musl-dev libffi-dev openssl-dev
          pip install --upgrade pip
          pip install pipenv
          pipenv install --system

      - name: Set Django settings module
        run: export DJANGO_SETTINGS_MODULE="coronavstech.settings"

      - name: Run tests fib
        run: pytest fibonacci -s -v --durations=0

      - name: Run app companies test
        run: pytest companies/tests -s -v --durations=0

